# Generated by Django 2.2.6 on 2019-10-24 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mood_sense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moods', to='mood_sense.Profile'),
        ),
    ]
