# Generated by Django 2.2.6 on 2019-10-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_sense', '0002_auto_20191024_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='characteristic',
            field=models.CharField(choices=[('2', 'happy'), ('0', 'sad'), ('1', 'neutral')], default='1', max_length=50),
        ),
    ]
