# Generated by Django 2.2.6 on 2019-10-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_sense', '0004_auto_20191024_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9),
        ),
        migrations.AlterField(
            model_name='mood',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10),
        ),
    ]
