# Generated by Django 2.2.6 on 2019-10-24 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mood_sense', '0006_auto_20191024_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='user',
        ),
        migrations.AddField(
            model_name='mood',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='moods', to='mood_sense.Profile'),
        ),
    ]
