# Generated by Django 2.2.6 on 2019-10-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_sense', '0008_auto_20191024_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='mood',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=21, null=True),
        ),
    ]
