# Generated by Django 2.2.6 on 2019-10-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_sense', '0009_auto_20191024_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='characteristic',
            field=models.CharField(choices=[('Happy', 'Happy'), ('No pain', 'No pain'), ('Very mild', 'Very mild'), ('Discomforting', 'Discomforting'), ('Tolerable', 'Tolerable'), ('Distressing', 'Distressing'), ('Very distressing', 'Very distressing'), ('Intense', 'Intense'), ('Very intense', 'Very intense'), ('Utterly horrible', 'Utterly horrible'), ('Excruciating unbearable', 'Excruciating unbearable'), ('Unimaginable unspeakable', 'Unimaginable unspeakable')], default='1', max_length=50),
        ),
    ]
