# Generated by Django 2.2.6 on 2019-10-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_sense', '0010_auto_20191024_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
