# Generated by Django 2.2.6 on 2019-10-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_sense', '0011_mood_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='location',
            field=models.CharField(default='Ukraine, Odessa', max_length=200),
        ),
    ]
